import{useEffect,useState}from'react';
import{api}from'../api/client';
import{CHARACTERS}from'../components/characters/characterCatalog';
import type{ModuleProgressData}from'../components/training/ModuleProgress';

export function PlayerMenuScreen({name,characterId,onCharacterChanged,onTrain,onSwitch}:{name:string;characterId:string;onCharacterChanged:()=>void;onTrain:()=>void;onSwitch:()=>void}){
 const[progress,setProgress]=useState<ModuleProgressData|null>(null);const[characterOpen,setCharacterOpen]=useState(false);const[nameOpen,setNameOpen]=useState(false);const[draftName,setDraftName]=useState(name);useEffect(()=>{api<ModuleProgressData>('/module-progress').then(setProgress).catch(()=>undefined)},[]);const choose=async(id:string)=>{await api('/profile/character',{method:'PATCH',body:JSON.stringify({character_id:id})});setCharacterOpen(false);onCharacterChanged()};const saveName=async(e:React.FormEvent)=>{e.preventDefault();await api('/auth/name',{method:'POST',body:JSON.stringify({name:draftName})});setNameOpen(false);onCharacterChanged()};const character=CHARACTERS.find(item=>item.id===characterId)??CHARACTERS[0];
 return <main className="menu-screen player-menu"><section className="hero-menu"><div className="player-heading"><img src={character.image} alt=""/><div><p className="eyebrow">Player ready</p><h1>{name}</h1><button className="quiet" onClick={()=>{setDraftName(name);setNameOpen(true)}}>Edit name</button></div></div><div className="status-panel"><span>Current module <b>{progress?.title??'Loading…'}</b></span><span>Module mastery <b>{progress?`${progress.progress_percent}%`:'—'}</b></span><span>Next focus <b>{progress?.criteria.introduced_key_mastery.map(item=>item.key.toUpperCase()).join(' / ')||'Steady rhythm'}</b></span></div><nav className="menu-actions" aria-label="Player menu"><button onClick={onTrain}>Continue training</button><button onClick={onTrain}>Quick warm-up</button><button disabled title="Available after weak-key evidence is collected">Practice weak keys</button><button onClick={onTrain}>New challenge</button><button className="quiet">Progress</button><button className="quiet" onClick={()=>setCharacterOpen(true)}>Character</button><button className="quiet">Settings</button><button className="quiet" onClick={onSwitch}>Switch player</button></nav></section>{characterOpen&&<div className="modal" role="dialog" aria-modal="true"><div><h2>Choose your character</h2><div className="character-picker">{CHARACTERS.map(item=><button key={item.id} onClick={()=>void choose(item.id)} aria-pressed={item.id===characterId}><img src={item.image} alt=""/><span>{item.name}</span></button>)}</div><button className="quiet" onClick={()=>setCharacterOpen(false)}>Cancel</button></div></div>}{nameOpen&&<div className="modal" role="dialog" aria-modal="true"><form onSubmit={e=>void saveName(e)}><h2>Edit player name</h2><input autoFocus value={draftName} maxLength={40} placeholder="MCP" onChange={e=>setDraftName(e.target.value)}/><button>Save name</button><button type="button" className="quiet" onClick={()=>setNameOpen(false)}>Cancel</button></form></div>}</main>;
}
