import {useEffect,useMemo,useState} from 'react';
import {createState,applyInput,pause,resume} from '../typing-core/engine';
import {accuracy,cadenceScore,grossWpm} from '../typing-core/metrics';
import {VisualKeyboard} from '../components/training/VisualKeyboard';
import {HandGuide} from '../components/training/HandGuide';
import {TrainingConsole} from '../components/ai/TrainingConsole';
import {coachNote,type CoachMode} from '../components/coach/coachRules';
import {CURRICULUM} from '../generated/curriculum.generated';
export function TrainingScreen(){const lessons=CURRICULUM.lessons;const[lessonIndex,setLessonIndex]=useState(0);const lesson=lessons[lessonIndex];const[state,setState]=useState(()=>createState(lesson.text));const[mode,setMode]=useState<CoachMode>('calm');const[hideMetrics,setHideMetrics]=useState(false);const reduceMotion=matchMedia('(prefers-reduced-motion: reduce)').matches;
useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.target instanceof HTMLInputElement||e.target instanceof HTMLButtonElement||e.target instanceof HTMLSelectElement)return;e.preventDefault();setState(s=>applyInput(s,{key:e.key,code:e.code,time:performance.now(),repeat:e.repeat,ctrlKey:e.ctrlKey,metaKey:e.metaKey,altKey:e.altKey}));};const blur=()=>setState(s=>pause(s,performance.now()));const focus=()=>setState(s=>resume(s,performance.now()));addEventListener('keydown',key);addEventListener('blur',blur);addEventListener('focus',focus);return()=>{removeEventListener('keydown',key);removeEventListener('blur',blur);removeEventListener('focus',focus)}},[]);
const metrics=useMemo(()=>({wpm:grossWpm(state.correctChars,state.activeMs),accuracy:accuracy(state.correctChars,state.attempts),cadence:cadenceScore(state.intervals)}),[state]);const reshuffle=()=>{const i=(lessonIndex+1)%lessons.length;setLessonIndex(i);setState(createState(lessons[i].text));};return <main><header className="topbar"><div><span className="mark">C</span><strong>Cadence</strong></div><div className="controls"><label>Coach <select value={mode} onChange={e=>setMode(e.target.value as CoachMode)}><option value="silent">Silent</option><option value="calm">Calm</option><option value="competitive">Competitive</option></select></label><label><input type="checkbox" checked={hideMetrics} onChange={e=>setHideMetrics(e.target.checked)}/> Hide live metrics</label></div></header><div className="shell"><section className="lesson"><p className="eyebrow">{lesson.stageId.replace('-',' ')} · technique first</p><h1>{lesson.title}</h1><p className="instruction">Keep your wrists relaxed. Find the F and J bumps, then look at the screen.</p>{!hideMetrics&&<div className="metrics"><span><b>{metrics.wpm.toFixed(0)}</b> WPM</span><span><b>{metrics.accuracy.toFixed(0)}%</b> accuracy</span><span><b>{metrics.cadence?.toFixed(0)??'—'}</b> cadence</span></div>}<div className="prompt" aria-label="Typing prompt">{[...state.prompt].map((c,i)=><span key={i} className={i<state.position?'done':i===state.position?'current':''}>{c===' '?'·':c}</span>)}</div><p className="position">{state.position} / {state.prompt.length}</p><VisualKeyboard active={state.prompt[state.position]} error={state.lastErrorKey??undefined}/><HandGuide target={state.prompt[state.position]??''} show={state.repeatErrors>=2} reduceMotion={reduceMotion}/>{state.complete&&<div className="complete"><h2>Round complete</h2><p>{coachNote(mode,metrics.accuracy,metrics.wpm)}</p><button onClick={reshuffle}>Next training round</button></div>}</section><TrainingConsole onReshuffle={reshuffle}/></div></main>}
