import{useEffect,useRef,useState}from'react';
import{api}from'../../api/client';
import{TRAINING_SHORTCUTS}from'../../config/shortcuts';

type Action={id:string;label:string;enabled:boolean;reason?:string|null};
type Options={capability_band:string;actions:Action[];passage_options:{durations_seconds:number[];topic_passages:boolean;long_form:boolean;numbers:boolean;symbols:boolean}};
type Status={state:'ready'|'builtin'|'connecting';lesson_generation_available:boolean};

export function TrainingConsole({open,onToggle,onAction,moduleTitle,modulePercent}:{open:boolean;onToggle:()=>void;onAction:(action:string,request?:string)=>void;moduleTitle:string;modulePercent:number}){
 const first=useRef<HTMLButtonElement>(null);const[input,setInput]=useState('');const[status,setStatus]=useState<Status|null>(null);const[options,setOptions]=useState<Options|null>(null);
 useEffect(()=>{if(!open)return;first.current?.focus();Promise.all([api<Status>('/ai/status'),api<Options>('/training/options')]).then(([s,o])=>{setStatus(s);setOptions(o)}).catch(()=>setStatus({state:'builtin',lesson_generation_available:false}))},[open]);
 if(!open)return <aside className="console collapsed"><p className="eyebrow">AI: {status?.state==='builtin'?'Built-in mode':'Ready'}</p><button title={`Open Training Console (${TRAINING_SHORTCUTS.toggleAI})`} aria-keyshortcuts="F1" onClick={onToggle}>Open Training Console <kbd>F1</kbd></button></aside>;
 const actions=options?.actions??[{id:'continue',label:'Continue the plan',enabled:true},{id:'reshuffle',label:'Give me another short pattern',enabled:true}];
 return <aside className="console expanded" aria-label="Training Console"><div className="console-head"><div><p className="eyebrow">Training console · {status?.state==='builtin'?'built-in mode':'AI ready'}</p><h2>{moduleTitle} · {modulePercent}% mastery</h2></div><button title={`Back to training (${TRAINING_SHORTCUTS.returnToTraining})`} aria-keyshortcuts="Escape" onClick={onToggle}>Back to training <kbd>Esc</kbd></button></div><p>You’re building this module one clean pattern at a time. Choose a training action; locked choices explain what evidence is still needed.</p>{status?.state==='builtin'&&<p className="notice">AI is unavailable right now. Built-in training is ready, so you can keep going.</p>}<div className="console-options">{actions.slice(0,4).map((action,index)=><button key={action.id} ref={index===0?first:undefined} disabled={!action.enabled} title={action.reason??(action.id==='reshuffle'?`Reshuffle (${TRAINING_SHORTCUTS.reshuffle})`:action.label)} aria-keyshortcuts={action.id==='reshuffle'?'F2':undefined} onClick={()=>onAction(action.id)}>{action.label}{action.id==='reshuffle'&&<kbd>F2</kbd>}{!action.enabled&&action.reason&&<small>{action.reason}</small>}</button>)}</div><form className="ai-input" onSubmit={event=>{event.preventDefault();const value=input.trim();if(value){onAction('custom_passage',value);setInput('')}}}><label>Something else…<input value={input} onChange={event=>setInput(event.target.value)} placeholder="Ask for a typing-focused change"/></label><button type="submit" disabled={!input.trim()}>Build practice</button></form></aside>;
}
