from pathlib import Path
import json
import re

ROOT = Path(__file__).resolve().parents[1]
SPEC = ROOT / 'LEARN_TO_TYPE_CODEX_BUILD_SPEC_REV10_64_MODULES_64_TEXTS.md'

def build_rev10_curriculum():
    source = SPEC.read_text(encoding='utf-8')
    rev10 = source[source.index('# REV10 —'):]
    pattern = re.compile(r'### Module (\d+) — (.*?)\n\n\*\*Focus:\*\* (.*?)\n\n\*\*Built-in text:\*\*\n\n> (.*?)(?=\n\n### Module|\n\n## 7\.)', re.S)
    entries = [(int(number), title.strip(), focus.strip(), ' '.join(text.split())) for number, title, focus, text in pattern.findall(rev10)]
    if len(entries) != 64 or [item[0] for item in entries] != list(range(1, 65)):
        raise RuntimeError('REV10 must contain exactly 64 ordered module entries')
    allowed = set(' ')
    stages, lessons = [], []
    authors = {'Poe: Suspense':'Edgar Allan Poe','Poe: The Raven':'Edgar Allan Poe','The Scarlet Letter':'Nathaniel Hawthorne','Moby-Dick':'Herman Melville','Huckleberry Finn':'Mark Twain','The Great Gatsby':'F. Scott Fitzgerald','The Red Badge of Courage':'Stephen Crane','The Call of the Wild':'Jack London','The Awakening':'Kate Chopin','Leaves of Grass':'Walt Whitman','Emily Dickinson':'Emily Dickinson','Frederick Douglass':'Frederick Douglass','The Crucible':'Arthur Miller','Of Mice and Men':'John Steinbeck','To Kill a Mockingbird':'Harper Lee','Fahrenheit 451':'Ray Bradbury'}
    for order, title, focus, text in entries:
        module_id, lesson_id = f'module_{order:02d}', f'builtin_{order:02d}'
        introduced = sorted({char.lower() for char in text if char.isalpha() and char.lower() not in allowed})
        allowed.update(char.lower() for char in text)
        if order >= 15: allowed.update('abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789 .,/?!\'":;+-()%')
        phase = 'foundation' if order <= 16 else 'fluency' if order <= 32 else 'literature' if order <= 48 else 'modern'
        source_type = 'typing_drill' if order <= 15 else 'original_commentary' if 33 <= order <= 48 else 'original_fiction' if order in {61, 62} else 'original'
        lesson = {'id': lesson_id, 'stageId': module_id, 'moduleId': module_id, 'title': title, 'text': text, 'sourceType': source_type, 'tags': [phase, source_type]}
        if 33 <= order <= 48:
            work = title
            lesson.update({'literatureWork': work, 'literatureAuthor': authors[work], 'tags': ['american_literature', 'high_school', 'original_commentary']})
        lessons.append(lesson)
        stages.append({'id': module_id, 'order': order, 'title': title, 'phase': phase, 'objective': focus, 'focus': focus, 'introducedKeys': introduced, 'allowedCharacters': ''.join(sorted(allowed)), 'minimumCompletedDrills': 2 if order <= 16 else 3, 'targetAccuracy': .90 if order <= 16 else .93 if order <= 32 else .95, 'targetMastery': .60 if order <= 16 else .72, 'maxHintRate': .20 if order <= 16 else .15, 'lessonIds': [lesson_id], 'builtInTextId': lesson_id, 'fallbackDrills': [text]})
    return {'version': '2026.10', 'stages': stages, 'lessons': lessons}

curriculum = build_rev10_curriculum()
finger_map = json.loads((ROOT/'shared/keyboard/finger-map.us-qwerty.json').read_text())
(ROOT/'shared/curriculum/curriculum.v1.json').write_text(json.dumps(curriculum, indent=2) + '\n', encoding='utf-8')

def ts(value, name):
    return f"// Generated by scripts/generate_shared.py. Do not edit.\nexport const {name} = {json.dumps(value, separators=(',', ':'))} as const;\n"

(ROOT/'frontend/src/generated').mkdir(parents=True, exist_ok=True)
(ROOT/'backend/app/curriculum').mkdir(parents=True, exist_ok=True)
(ROOT/'frontend/src/generated/curriculum.generated.ts').write_text(ts(curriculum, 'CURRICULUM'), encoding='utf-8')
(ROOT/'frontend/src/generated/finger-map.generated.ts').write_text(ts(finger_map, 'FINGER_MAP'), encoding='utf-8')
(ROOT/'backend/app/curriculum/generated_curriculum.py').write_text('# Generated by scripts/generate_shared.py. Do not edit.\nCURRICULUM = '+repr(curriculum)+'\n', encoding='utf-8')
