from pathlib import Path
import json

ROOT = Path(__file__).resolve().parents[1]
curriculum = json.loads((ROOT/'shared/curriculum/curriculum.v1.json').read_text())
finger_map = json.loads((ROOT/'shared/keyboard/finger-map.us-qwerty.json').read_text())

def ts(value, name):
    return f"// Generated by scripts/generate_shared.py. Do not edit.\nexport const {name} = {json.dumps(value, separators=(',', ':'))} as const;\n"

(ROOT/'frontend/src/generated').mkdir(parents=True, exist_ok=True)
(ROOT/'backend/app/curriculum').mkdir(parents=True, exist_ok=True)
(ROOT/'frontend/src/generated/curriculum.generated.ts').write_text(ts(curriculum, 'CURRICULUM'))
(ROOT/'frontend/src/generated/finger-map.generated.ts').write_text(ts(finger_map, 'FINGER_MAP'))
(ROOT/'backend/app/curriculum/generated_curriculum.py').write_text('# Generated by scripts/generate_shared.py. Do not edit.\nCURRICULUM = '+repr(curriculum)+'\n')

